#!/bin/sh

# User-configurable bits. FIXME: read these from the Pygr config file!
megatestdir='/result/pygr_megatest'
mycnfpath="${megatestdir}"
logdir="${megatestdir}"
#


# It's easier to edit PATH than to change explicit paths all over the script...
PATH='/usr/kerberos/sbin:/usr/kerberos/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin'

# $HOME must be set in order for MySQL code to be able to find per-user option
# file (i.e. ~/.my.cnf). This is necessary in two cases:
#  - if you actually want to use that file;
#  - if you build Pygr against certain (older?) versions of the MySQL client,
#      which segfault on startup if $HOME is unset or empty
if [ -z "$HOME" ]; then
	HOME="${mycnfpath}"
	export HOME
fi

# Tell Python where Pygr will live.
arch=`uname -m`
pver=`python -V 2>&1 | cut -f2 -d' ' | cut -f1-2 -d'.'`	# FIXME: must be a cleaner way of doing this... awk?
PYTHONPATH="${megatestdir}/src_save/pygr/build/lib.linux-${arch}-${pver}"
export PYTHONPATH
unset arch pver

cd "${megatestdir}/src_save"
if [ $? -ne 0 ]; then
	echo "Error: Couldn't cd to ${megatestdir}/src_save, aborting"
	exit 1
fi

# Step 1: download and build Pygr
date &> "${logdir}/tmp1_megatest.log"
rm -rf pygr
git clone -q 'git://repo.or.cz/pygr.git' &> /dev/null
cd pygr
python setup.py build &> "${logdir}/tmp0_megatest.log"

# Step 2: run tests
cd tests
python runtest.py &> "${logdir}/tmp2_megatest.log"
echo "$PYTHONPATH" &> "${logdir}/tmp3_megatest.log"
cd oldtests
python protest.py *megatest.py &> "${logdir}/tmp4_megatest.log"

# Step 3: send report and clean up
date &> "${logdir}/tmp5_megatest.log"
cd ..
python tools/send_megatest_email.py
cd ../..
rm -rf pygr
rm -f "${logdir}/tmp*megatest.log"

exit 0
